Cargo.lock
Cargo.toml
crates/warg-server/Cargo.toml
crates/warg-server/readme.md
crates/warg-server/src/content.rs
crates/warg-server/src/lib.rs
crates/warg-server/src/main.rs

This commit adds a Axum-based HTTP server which currently just has simple content upload and download handlers for demo purposes.

Add warg-server crate

---

Cargo.lock
crates/api/Cargo.toml
crates/api/src/content.rs
crates/api/src/fetch.rs
crates/api/src/lib.rs
crates/api/src/package.rs
crates/api/src/proof.rs
crates/client/Cargo.toml
crates/client/src/api.rs
crates/client/src/lib.rs
crates/server/Cargo.toml
crates/server/src/api/content.rs
crates/server/src/api/fetch.rs
crates/server/src/api/package.rs
crates/server/src/api/proof.rs
crates/server/src/services/core.rs

This PR the serializable API types from the server crate into a
`warg-api` crate.
The client and server now share these types via the `warg-api` crate.
This change allows crates dependent upon the `warg-client` crate to not have to
build server-related dependencies.

Refactor API types into a `warg-api` crate.

---

Cargo.lock
Cargo.toml
crates/api/Cargo.toml
crates/client/Cargo.toml
crates/crypto/Cargo.toml
crates/crypto/src/signing/private_key.rs
crates/crypto/src/signing/public_key.rs
crates/crypto/src/signing/signature.rs
crates/protocol/Cargo.toml
crates/protocol/src/proto_envelope.rs
crates/server/Cargo.toml
crates/transparency/Cargo.toml

This PR updates the workspace to use the relatively-new workspace dependencies feature of cargo.
This allows the top-level `Cargo.toml` to contain dependency information shared across the entire workspace.
Additionally, all dependencies have been upgraded to the latest versions.

Use workspace dependencies feature.

---

crates/api/src/content.rs
crates/client/src/lib.rs
crates/server/src/api/package.rs
src/bin/warg-cli.rs
src/commands.rs
src/commands/info.rs

Adds command analogous to `yarn info`, printing versions and other stats about a package.
Initially I'm just enabling the printing of the version numbers that exist for a given package, but could easily add any other info that anybody identifies as significant.

add info command

---

Cargo.lock
crates/api/Cargo.toml
crates/api/src/content.rs
crates/api/src/fetch.rs
crates/api/src/lib.rs
crates/api/src/package.rs
crates/api/src/proof.rs
crates/client/src/api.rs
crates/client/src/lib.rs
crates/server/Cargo.toml
crates/server/src/api/content.rs
crates/server/src/api/fetch.rs
crates/server/src/api/package.rs
crates/server/src/api/proof.rs
crates/server/src/lib.rs
crates/server/src/main.rs
crates/server/src/services/core.rs
crates/server/src/services/data/log.rs
crates/server/src/services/data/map.rs
crates/server/src/services/data/mod.rs
src/bin/warg-cli.rs

This PR adds error enumerations to the `api` crate that are shared between the server and client implementations.
Both the client and server crates have been updated to use the error enums.

Implement error enums in the `api` crate.

---

crates/api/src/fetch.rs
crates/api/src/package.rs
crates/server/src/api/fetch.rs
crates/server/src/api/package.rs
crates/server/src/services/core.rs

This commit improves the error message displayed when fetching a log for a nonexistent package.
Previously it would print out the log id of the missing package, which isn't very friendly.
This commit allows the fetch API to return an error of the package name, specifically for fetching logs.

Improve fetch API error message when fetching logs for nonexistent package.

---

.vscode/settings.json

Build seemed to work, but vscode rust-analyzer claimed error.
- workaround for #106

fix: use postgres feature in vscode for analyzer workaround

---

README.md
ci/run-postgres-tests.sh
crates/server/README.md
crates/server/src/bin/warg-server.rs
demo/setup-server.sh
docker-compose.yaml
infra/local/secrets.inc.sh
tests/postgres/mod.rs

This commit prefixes all environment variables respected in the server CLI to use a `WARG_` prefix.
Also does the same for an environment variable used in Postgres tests.

Prefix all environment variables used by the server with `WARG_`.

---

docker-compose.yaml
infra/local/down.sh
infra/local/locals.inc.sh
infra/local/rebuild.sh
infra/local/stop.sh
infra/local/up.sh

Docker Compose v2 was released in 2020 and switched to `docker compose` instead of `docker-compose` on the CLI.
The docker-compose.yaml also needed a few changes. Per docker [docs](https://docs.docker.com/compose/migrate/) and [here](https://docs.docker.com/compose/history/), `version` is ignored should be omitted and `name` field should be removed here.
Also, fixed a name mismatch on the database container `registry-db-1 ` vs `bytecodealliance-registry-db-1`.

Fix for docker compose v2

---

crates/server/openapi.yaml

[Rendered API documentation](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/bytecodealliance/registry/62d8a9cfaa4ce424740c10d76d640b906836d753/crates/server/openapi.yaml)
This PR creates a single OpenAPI specification for the Warg registry server.
It is intended to (ultimately) be the complete specification of a Warg registry server's REST API.
The specification proposed here is not what is currently implemented by `warg-server`, but it is inspired heavily by both the existing implementation and previously proposed APIs.
We can use this as a starting point to finalize an API specification for the initial version.
An API around streaming records to federated registries is not currently included in the specification, so design around this is welcome.

Add an `openapi.yaml` file to the server implementation.

---

.vscode/settings.json
crates/server/Cargo.toml
crates/server/src/api/debug/mod.rs
crates/server/src/api/mod.rs
crates/server/src/api/v1/mod.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/mod.rs
crates/server/src/datastore/postgres/mod.rs

This introduces a 'debug' feature to warg-server, which toggles on /debug/-prefixed APIs. The first such api is /debug/packages, which uses a new (optional) DataStore::debug_list_package_ids.
Reorganized some generic API code from `warg_server::api::v1` up to `warg_server::api` to be shared with the new `warg_server::api::debug` module.

server: Add /debug/packages endpoint

---

.github/workflows/main.yml
crates/server/src/datastore/postgres/mod.rs

I missed this in rebasing several PRs, and CI wasn't testing with the `warg-server/debug` feature enabled. This fixes both of those problems.

Fix logical merge conflict under debug feature

---

crates/api/src/v1/fetch.rs
crates/client/src/lib.rs
crates/server/openapi.yaml
crates/server/src/api/v1/fetch.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/mod.rs
crates/server/src/datastore/postgres/mod.rs

`checkpoint_id` is probably more clear and consistent than `root` or `checkpoint`. Breaking change while they are still easy.
I don't feel strongly about this. This PR would be an "either or", comparing against: https://github.com/bytecodealliance/registry/pull/161

rename `root` field to `checkpoint_id` for the API call to fetch logs

---

Cargo.lock
Cargo.toml
crates/server/diesel.toml
crates/server/src/datastore/postgres/schema.rs

This PR bumps the dependencies to latest.
It includes the latest `wasmparser` and `indexmap` (bumped in other dependencies to 2.0.0).

Bump dependencies.

---

Cargo.lock
Cargo.toml
crates/api/src/v1/package.rs
crates/crypto/src/hash/static.rs
crates/protocol/src/serde_envelope.rs
crates/server/openapi.yaml
crates/server/src/api/v1/package.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/mod.rs
crates/server/src/datastore/postgres/migrations/2023-04-11-013700_initial_db/up.sql
crates/server/src/datastore/postgres/mod.rs
crates/server/src/datastore/postgres/models.rs
crates/server/src/datastore/postgres/schema.rs
crates/server/src/lib.rs
crates/server/src/services/core.rs
crates/transparency/src/log/vec_log.rs
tests/postgres/mod.rs
tests/support/mod.rs

Prior to this commit, every published record is associated with the first checkpoint created after the record was added to the registry log. While this does aid clients in verifying the inclusion of a record, it is more information than necessary and forces the registry to hold on to all checkpoints indefinitely. It also requires additional bookkeeping just to track this partially-unnecessary information.
This removes that per-record checkpoint and instead associates each record with its index in the registry log. This is still enough information to aid inclusion proofs and reduces the overall complexity of the server.

Replace record checkpoint field with registry log index

---

crates/client/src/storage/fs.rs
tests/client.rs

Fixing `warg update` in #158 introduced a regression when local registry storage is empty.

client: Fix Client::update on empty registry storage

---

.gitignore
Cargo.lock
crates/api/Cargo.toml
crates/api/src/v1/package.rs
crates/api/src/v1/paths.rs
crates/client/src/api.rs
crates/client/src/config.rs
crates/client/src/lib.rs
crates/client/src/registry_url.rs
crates/server/openapi.yaml
crates/server/src/api/v1/package.rs
src/commands.rs
src/commands/config.rs
src/commands/key.rs
src/keyring.rs

This implements the proposal here: https://github.com/bytecodealliance/registry/discussions/160 It adapts _some_ of #137. Notably it does _not_ add a "patch record" operation as I think that conflicts with #146.
I also fell down a bit of a rabbit hole to allow upload URLs to be specified relative to the registry URL which led to a refactor that [adds a `RegistryUrl` type](https://github.com/bytecodealliance/registry/pull/167/commits/30d900f0d9a39c591c9d0864efd53ace31e6ccd7). Note that this will (probably) break existing client config for `localhost` environments as it makes port numbers significant for on-disk paths and the keyring.

Update missing content API

---

crates/api/src/v1/proof.rs
crates/client/src/api.rs
crates/client/src/lib.rs
crates/client/src/storage.rs
crates/client/src/storage/fs.rs
crates/protocol/src/registry.rs
crates/server/openapi.yaml
crates/server/src/api/debug/mod.rs
crates/server/src/api/v1/fetch.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/mod.rs
crates/server/src/datastore/postgres/migrations/2023-08-11-183810_add_checkpoints_timestamp/down.sql
crates/server/src/datastore/postgres/migrations/2023-08-11-183810_add_checkpoints_timestamp/up.sql
crates/server/src/datastore/postgres/mod.rs
crates/server/src/datastore/postgres/models.rs
crates/server/src/datastore/postgres/schema.rs
crates/server/src/services/core.rs
tests/memory/mod.rs
tests/postgres/mod.rs
tests/server.rs

- Add a new TimestampedCheckpoint type, which adds a unix timestamp to the basic checkpoint data.
- Update DataStores to store TimestampedCheckpoints.
- Update CoreService to generate new TimestampedCheckpoint periodically, even if the underlying checkpoint hasn't changed.
This also renames `MapCheckpoint` to just `Checkpoint`. `MapCheckpoint` was slightly misleading since it covers both the verifiable map *and* log.

Add timestamp to checkpoints

---

crates/client/src/lib.rs
crates/crypto/src/signing/private_key.rs
crates/protocol/src/package/state.rs
crates/server/src/policy/record/authorization.rs

This adds a `delegation` flag to AuthorizedKeyPolicy which is configurable per-namespace/package. When enabled, the authorized key enforcement for that scope only applies to init messages.
To support the flag, the authorized keys toml format has changed to e.g.:
```toml
[namespace.foo]
keys = ["..."]
delegation = true
```
Fixes #185
Also a couple of formatting changes from rustfmt 1.6 since we enforce latest stable.

Support delegation in AuthorizedKeyPolicy

---

.gitignore
crates/api/src/v1/fetch.rs
crates/api/src/v1/package.rs
crates/api/src/v1/proof.rs
crates/client/src/api.rs
crates/client/src/lib.rs
crates/client/src/storage.rs
crates/protocol/src/lib.rs
crates/protocol/src/proto_envelope.rs
crates/protocol/src/registry.rs
crates/server/openapi.yaml
crates/server/src/api/debug/mod.rs
crates/server/src/api/v1/fetch.rs
crates/server/src/api/v1/package.rs
crates/server/src/api/v1/proof.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/mod.rs
crates/server/src/datastore/postgres/mod.rs
crates/server/src/datastore/postgres/schema.rs
crates/server/src/services/core.rs
tests/postgres/mod.rs

The registry index for a published record is going to be different than the `VecLog`'s `Node(usize)` value that is required for the log inclusion proof. For now, keeping the existing pattern of using a `HashMap` (could be a `Vec` if added back in the same order) to lookup the value in memory.
To make it easier to adjust the size of the integer for the `log_length` and `registry_index`, I added a type alias `RegistryIndex`.
As always, suggestions appreciated. This was more of a change than I expected.

added registry index for fetched records and updated proof endpoints to use the log length and registry index

---

crates/server/openapi.yaml

publish package record endpoint to reflect the JSON field "id" instead of "name"

fixed openapi.yaml

---

crates/api/src/v1/package.rs
crates/server/src/api/v1/package.rs

Currently, requires `contentSources` JSON field to be provided even if it is empty. This makes it optional and matches the OpenAPI spec.

publish record endpoint changes contentSources to optional JSON field

---

crates/api/src/v1/package.rs

This fixes a mismatch between the intended JSON schema, described in the [OpenAPI spec](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/bytecodealliance/registry/main/crates/server/openapi.yaml#tag/package/operation/getPackageRecord), and the implementation.

added missing serde flatten

---

.github/workflows/main.yml
Cargo.toml
crates/api/Cargo.toml
crates/client/Cargo.toml
crates/crypto/Cargo.toml
crates/protocol/Cargo.toml
crates/server/Cargo.toml
crates/transparency/Cargo.toml
proto/Cargo.toml

This PR is going into the `release-0.1.0` branch (off of the `v0.1.0` tag), which, when ready, will contain everything for the 0.1.0 crates to be published.
To start, this updates the various `Cargo.toml` for fields related to publishing. The next step is creating a publish script for a GitHub action to auto publish with.
Please 🚲 🏠  on the crate descriptions a bit.

Update crates for publishing.

---

Cargo.lock
crates/api/src/v1/fetch.rs
crates/client/src/lib.rs
crates/client/src/storage.rs
crates/server/openapi.yaml
crates/server/src/api/v1/fetch.rs

This changes the `POST /v1/fetch/logs` endpoint to use a server implementation defined `fetchToken` for the last known record instead of the `RecordId`. It still can be the `RecordId`, but it doesn't need to be. In fact, the reference implementation still uses the `RecordId` for the `fetchToken`.
The motivation here is to give server implementations greater flexibility on implementing the fetch logs endpoint.
Also, in this PR, the Client CLI will be more resilient in handling records that are returned that it has already seen before.

fetch logs endpoint using fetch token String

---

.github/workflows/publish-to-crates-io.yml
.gitignore
ci/publish.rs

This PR adds a GitHub action that automatically publishes crates upon the creation of a new tag.
It is heavily based off of what Wasmtime does to publish crates.
To run the publish script manually:
* rustc ci/publish.rs
* ./publish \<cmd>
Where \<cmd> may be:
* `bump` or `bump-patch` to automatically bump the versions of crates in the repository.
* `verify` to verify all crates can be published.
* `publish` to actually publish the crates to crates-io.

Add GitHub action for automatically publishing crates.

---

Cargo.lock
Cargo.toml
crates/api/Cargo.toml

This PR sets the `warg-api` crate version to 0.1.1.
I accidentally published a 0.1.0 placeholder crate for the `warg-api` crate, which has now been yanked.
To workaround this, `warg-api` will be at 0.1.1 and the rest of the crates will be 0.1.0 until a 0.2.0 release.

Bump `warg-api` crate version.

---

README.md
crates/api/src/v1/content.rs
crates/api/src/v1/mod.rs
crates/api/src/v1/package.rs
crates/api/src/v1/paths.rs
crates/client/src/api.rs
crates/client/src/lib.rs
crates/client/src/storage.rs
crates/client/src/storage/fs.rs
crates/protocol/src/registry.rs
crates/server/openapi.yaml
crates/server/src/api/v1/content.rs
crates/server/src/api/v1/mod.rs
crates/server/src/api/v1/package.rs
src/bin/warg.rs
src/commands.rs
src/commands/clear.rs
src/commands/reset.rs
tests/server.rs

Proposed breaking changes to the API:
1. `GET /v1/content/{digest}` endpoint instead of `GET /v1/package/{logId}/record/{recordId}` for getting content source download URLs;
Current API is not ideal, since records can have multiple releases which provides more download links than clients likely want. Also, when Wasm naked imports are implemented, this new endpoint could more cleanly be extended to provide the dependency URLs for each digest.
2. Upload HTTP URLs can now specific the `method` and `headers`, so that can use `POST` or `PUT` as well as `Authorization` and `Content-Type` headers; In the future, it would be helpful to add multipart upload support for large files as a new variant type;
3. Download HTTP URLs can specify whether the `Range` header is supported to download pieces of …

Proposed changes before release

---

crates/api/src/v1/mod.rs
crates/api/src/v1/package.rs

`rename_all` as an attribute on an enum is renaming all the variants of the enum, not all the fields of those variants
https://github.com/bytecodealliance/registry/issues/221

missing serde rename for camelCase on the enum variants

---

README.md
crates/api/src/v1/fetch.rs
crates/api/src/v1/package.rs
crates/client/src/api.rs
crates/client/src/lib.rs
crates/client/src/storage.rs
crates/client/src/storage/fs.rs
crates/protocol/src/operator/state.rs
crates/protocol/src/registry.rs
crates/server/openapi.yaml
crates/server/src/api/debug/mod.rs
crates/server/src/api/v1/package.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/mod.rs
crates/server/src/datastore/postgres/mod.rs
crates/server/src/policy/record/authorization.rs
crates/server/src/policy/record/mod.rs
src/bin/warg.rs
src/commands/download.rs
src/commands/info.rs
src/commands/publish.rs
src/commands/run.rs
tests/client.rs
tests/postgres/mod.rs
tests/server.rs
tests/support/mod.rs

Implements #229 
Should not have breaking changes. Using `serde` alias for both the API schema change for the publish package record endpoint as well as the client storage JSON objects.

rename `PackageId` to `PackageName` on issue #229

---

crates/client/src/lib.rs

This PR makes `download_content` a public function from `Client`.
It turns out that this is a useful function to have for clients that can determine missing content hashes from the client storage and instruct the client to download just the content.

Make `download_content` public in `Client`.

---

crates/client/src/lib.rs

Client will skip the prove consistency request if the previous checkpoint is still the latest checkpoint. This fixes an error when `from` and `to` are the same `log_length`.

fix for client to skip the prove consistency request if checkpoint is unchanged

---

crates/client/Cargo.toml

Adding this in order to be able to cross-compile `cargo-component` and publishing more arch binaries on releases

chore: add capability to use vendored openssl

---

crates/client/src/lib.rs
crates/protocol/src/package/state.rs

Added method to determine what permissions a given `KeyID` has for a package.

added `key_permissions` method to package LogState

---

src/commands/login.rs
src/keyring.rs

Now `warg login` sets home url based on registry flag and generates a default key if one doesn't already exist.
Also contains a fix to only use home url if it has been explicitly set

login sets default url with arg and creates default key if absent

---

crates/api/src/v1/mod.rs
crates/api/src/v1/package.rs
crates/client/src/storage.rs

Drop temporary aliasing, per release policy  #221

removed temporary aliases in struct fields with serde

---

Cargo.lock
Cargo.toml
ci/publish.rs
crates/client/src/api.rs
crates/client/src/config.rs
crates/credentials/Cargo.toml
crates/credentials/src/keyring.rs
crates/credentials/src/lib.rs
src/commands.rs
src/commands/config.rs
src/commands/key.rs
src/commands/login.rs
src/commands/logout.rs
src/lib.rs
tests/support/mod.rs

Adds a new crate exposing methods for accessing credentials in the keyring so that consumers don't need to implement it too.
This also checks for auth tokens less eagerly, avoiding a keyring password if the user hasn't set an auth token.

Warg credentials

---

crates/api/src/v1/fetch.rs
crates/client/src/lib.rs
crates/server/openapi.yaml
crates/server/src/api/v1/fetch.rs

The intention of adding this field is to handle moved repositories. When a repository is moved, Warg will use the new repository name instead, but the users must be alerted so they can update their dependency list.
Closes https://github.com/bytecodealliance/registry/issues/261

Add warning field to fetch logs response.

---

crates/client/src/lib.rs
crates/protocol/src/operator/state.rs
crates/protocol/src/registry.rs
crates/server/src/datastore/memory.rs
crates/server/src/datastore/postgres/mod.rs
tests/memory/mod.rs
tests/postgres/mod.rs
tests/server.rs

see issue [#245](https://github.com/bytecodealliance/registry/issues/245)

package namespace and name validation enforces lowercase only

---

Cargo.lock
crates/client/src/keyring.rs
crates/crypto/src/hash/static.rs
crates/crypto/src/signing/public_key.rs
crates/protocol/tests/operator.rs
crates/protocol/tests/package.rs
crates/server/src/datastore/postgres/models.rs

Remove some unused imports, use `clone_from` where appropriate, allow unread fields on a Postgres-related structure, and fix a `#[cfg(feature = ...)]` referencing a non-existent feature.

Clean up some clippy warnings

---

crates/client/src/config.rs
crates/client/src/keyring.rs
crates/client/src/keyring/error.rs
crates/client/src/keyring/mod.rs
crates/client/src/lib.rs
src/commands.rs
src/commands/config.rs
src/commands/key.rs
src/commands/login.rs
src/commands/logout.rs
tests/support/mod.rs

Makes keyring backends user-selectable, as discussed in https://github.com/bytecodealliance/registry/issues/271#issuecomment-2100908799.

Configurable keyring backends

---

Cargo.lock
Cargo.toml

This is a network optimization for some regions (mainland China), providing `socks5` support for the warg protocol and downstream tools.
---
Accessing the global warg server without socks proxy has a high probability of being randomly blocked.
This phenomenon has been confirmed in Shanghai, China and Beijing, China.
The error content is
```yaml
error: failed to send request to registry server: error sending request for url (https://wa.dev/v1/fetch/checkpoint): error trying to connect: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)
Caused by:
0: error sending request for url (https://wa.dev/v1/fetch/checkpoint): error trying to connect: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)
1: error trying to connect: tcp connect error: …
```

Enable socks proxy to optimize network connection

---

crates/client/src/keyring/error.rs
crates/client/src/keyring/flatfile.rs
crates/client/src/keyring/mod.rs

This adds support for storing warg credentials as flat files in the warg config directory, following up on #278.

Implement flat-file keyring backend

---

src/commands/config.rs
src/commands/download.rs
src/commands/info.rs
src/commands/login.rs
src/commands/logout.rs

- `warg config` now lets you modify your current settings instead of forcing an overwrite
- `warg login --registry` asks you if you want to set that registry as your home / default registry
- Clearer messaging on the CLI on what registry is being used

improved `login` and `config` subcommands

---

crates/client/src/config.rs
crates/client/src/lib.rs
src/commands/publish.rs

- added a client method `sign_with_keyring_and_publish` ("keyring" feature required), making it easier for other crates that use the `warg-client` enable publishing
- when `warg publish yank`, adds a confirmation and more description #289 #264

Client publish improvement and yank confirmation

---

crates/api/src/lib.rs
crates/client/src/api.rs
crates/client/src/config.rs
crates/client/src/lib.rs
crates/client/src/registry_url.rs
src/commands.rs
src/commands/bundle.rs
src/commands/clear.rs
src/commands/config.rs
src/commands/dependencies.rs
src/commands/download.rs
src/commands/info.rs
src/commands/lock.rs
src/commands/login.rs
src/commands/logout.rs
src/commands/publish.rs
src/commands/reset.rs
src/commands/update.rs
tests/client.rs
tests/depsolve.rs
tests/postgres/mod.rs
tests/server.rs
tests/support/mod.rs

- Added Warg client support for `.well-known` path, which required the `warg_client::FileSystemClient::new_with_config()` methods to be `async`;
- Support both `warg login <registry-url>` and `warg login --registry <registry-url>` (also for `warg logout`);
- Sets the default registry, without configuration, to be `bytecodealliance.org`; [See discussions](https://github.com/bytecodealliance/wasm-pkg-tools/discussions/3#discussioncomment-9359731)
Follow on work to respect HTTP cache headers.

Well known config

---

crates/client/src/keyring/error.rs

- typo fix `keyring-backend` instead of `keyring_backend`
- reworded the error message

Fix typo and improve keyring error message

---

README.md

The getting started in the readme is missing an argument :)

fix missing arg in README command

---

Cargo.lock
Cargo.toml

Bumping `ptree` to `0.5.0` in order to pull in `config` `0.14.0`, which addresses some outstanding security issues:
Before:
```
Scanned old.spdx.json as SPDX SBOM and found 490 packages
╭─────────────────────────────────────┬──────┬───────────┬──────────────┬─────────┬───────────────────╮
│ OSV URL                             │ CVSS │ ECOSYSTEM │ PACKAGE      │ VERSION │ SOURCE            │
├─────────────────────────────────────┼──────┼───────────┼──────────────┼─────────┼───────────────────┤
│ https://osv.dev/RUSTSEC-2021-0139   │      │ crates.io │ ansi_term    │ 0.12.1  │ all-old.spdx.json │
│ https://osv.dev/RUSTSEC-2021-0145   │      │ crates.io │ atty         │ 0.2.14  │ all-old.spdx.json │
│ https://osv.dev/GHSA-g98v-hv3f-hcfr │      │           │              │         │ …
```

chore: Bump ptree to update config dependency

---

Cargo.lock
Cargo.toml

This brings in changes from [ptree#10](https://gitlab.com/Noughmad/ptree/-/merge_requests/10), which addresses [RUSTSEC-2021-0145](https://rustsec.org/advisories/RUSTSEC-2021-0145.html).
Please note that there's [another change pending for `ptree`](https://gitlab.com/Noughmad/ptree/-/merge_requests/11) to address [RUSTSEC-2021-0139](https://rustsec.org/advisories/RUSTSEC-2021-0139.html), but since that hasn't yet been merged, I figured it was worth going ahead and getting at least this bump in.

chore: Bump ptree 0.5.1

---

Cargo.lock
Cargo.toml

This addresses [`RUSTSEC-2021-0139`](https://rustsec.org/advisories/RUSTSEC-2021-0139.html)

chore: Bump ptree 0.5.2

---

.github/workflows/main.yml

I noticed https://github.com/bytecodealliance/registry/pull/311 was failing on the `diesel_cli` install step.
Digging in a bit, I noticed the [`ubuntu-latest` runner image was changed](https://github.com/actions/runner-images/issues/10636) to point from [Ubuntu 22.04, which has `libsqlite3-dev` installed by default](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#installed-apt-packages), to [Ubuntu 24.04 instead and that no longer includes `libsqlite3-dev` in the default apt packages](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#installed-apt-packages).
This simply adjusts the features that are enabled from defaults to just `postgres`, which is what the CI workflow uses.
Additionally I folded in the changes …

chore(ci): Install diesel_cli with just postgres feature
